package dev.microcontrollers.rendertweaks.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import dev.isxander.yacl3.config.v2.api.ConfigClassHandler;
import dev.isxander.yacl3.config.v2.api.SerialEntry;
import dev.isxander.yacl3.config.v2.api.serializer.GsonConfigSerializerBuilder;
import dev.isxander.yacl3.gui.controllers.ColorController;
import dev.isxander.yacl3.platform.YACLPlatform;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.*;

public class RenderTweaksConfig {
    public static final ConfigClassHandler<RenderTweaksConfig> CONFIG = ConfigClassHandler.createBuilder(RenderTweaksConfig.class)
            .serializer(config -> GsonConfigSerializerBuilder.create(config)
                    .setPath(YACLPlatform.getConfigDir().resolve("rendertweaks.json"))
                    .build())
            .build();

    @SerialEntry public boolean disableLightning = false;
    @SerialEntry public Color lightningColor = new Color(0.45F, 0.45F, 0.5F, 0.3F);
    @SerialEntry public float lightningAlpha = 102;
    @SerialEntry public boolean lightningChroma = false;
    @SerialEntry public float lightningSaturation = 1F;
    @SerialEntry public float lightningBrightness = 1F;
    @SerialEntry public float lightningSpeed = 0.25F;

    @SerialEntry public boolean disableFishingLine = false;
    @SerialEntry public Color fishingLineColor = new Color(-16777216);
    @SerialEntry public float fishingLineAlpha = 102;
    @SerialEntry public boolean fishingLineChroma = false;
    @SerialEntry public float fishingLineSaturation = 1F;
    @SerialEntry public float fishingLineBrightness = 1F;
    @SerialEntry public float fishingLineSpeed = 0.25F;

    @SerialEntry public boolean disableWorldBorderStationary = false;
    @SerialEntry public Color worldBorderStationaryColor = new Color(2138367);
    @SerialEntry public float worldBorderStationaryAlpha = 102;
    @SerialEntry public boolean worldBorderStationaryChroma = false;
    @SerialEntry public float worldBorderStationarySaturation = 1F;
    @SerialEntry public float worldBorderStationaryBrightness = 1F;
    @SerialEntry public float worldBorderStationarySpeed = 0.25F;

    @SerialEntry public boolean disableWorldBorderShrinking = false;
    @SerialEntry public Color worldBorderShrinkingColor = new Color(16724016);
    @SerialEntry public float worldBorderShrinkingAlpha = 102;
    @SerialEntry public boolean worldBorderShrinkingChroma = false;
    @SerialEntry public float worldBorderShrinkingSaturation = 1F;
    @SerialEntry public float worldBorderShrinkingBrightness = 1F;
    @SerialEntry public float worldBorderShrinkingSpeed = 0.25F;

    @SerialEntry public boolean disableWorldBorderGrowing = false;
    @SerialEntry public Color worldBorderGrowingColor = new Color(4259712);
    @SerialEntry public float worldBorderGrowingAlpha = 102;
    @SerialEntry public boolean worldBorderGrowingChroma = false;
    @SerialEntry public float worldBorderGrowingSaturation = 1F;
    @SerialEntry public float worldBorderGrowingBrightness = 1F;
    @SerialEntry public float worldBorderGrowingSpeed = 0.25F;

    public static Screen configScreen(Screen parent) {
        return YetAnotherConfigLib.create(CONFIG, ((defaults, config, builder) -> builder
                .title(Component.translatable("rendertweaks.rendertweaks"))

                // Lightning

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("rendertweaks.lightning-bolt"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("rendertweaks.lightning-bolt"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.disable"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.lightning-bolt.disable.description")))
                                        .binding(false, () -> config.disableLightning, newVal -> config.disableLightning = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("rendertweaks.solid-color"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.solid-color.description")))
                                        .binding(defaults.lightningColor, () -> config.lightningColor, value -> config.lightningColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.enable-chroma"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.enable-chroma.description")))
                                        .binding(defaults.lightningChroma, () -> config.lightningChroma, newVal -> config.lightningChroma = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.saturation"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.saturation.description")))
                                        .binding(1F, () -> config.lightningSaturation, newVal -> config.lightningSaturation = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.brightness"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.brightness.description")))
                                        .binding(1F, () -> config.lightningBrightness, newVal -> config.lightningBrightness = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.alpha"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.alpha.description")))
                                        .binding(255F, () -> config.lightningAlpha, newVal -> config.lightningAlpha = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.0f", value)))
                                                .range(0F, 255F)
                                                .step(1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.speed"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.speed.description")))
                                        .binding(0.25F, () -> config.lightningSpeed, newVal -> config.lightningSpeed = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .build())
                        .build())

                // Fishing Line

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("Fishing Line"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Fishing Line"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.disable"))
                                        .description(OptionDescription.of(Component.literal("Completely removes fishing lines visually.")))
                                        .binding(false, () -> config.disableFishingLine, newVal -> config.disableFishingLine = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("rendertweaks.solid-color"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.solid-color.description")))
                                        .binding(defaults.fishingLineColor, () -> config.fishingLineColor, value -> config.fishingLineColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.enable-chroma"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.enable-chroma.description")))
                                        .binding(defaults.fishingLineChroma, () -> config.fishingLineChroma, newVal -> config.fishingLineChroma = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.saturation"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.saturation.description")))
                                        .binding(1F, () -> config.fishingLineSaturation, newVal -> config.fishingLineSaturation = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.brightness"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.brightness.description")))
                                        .binding(1F, () -> config.fishingLineBrightness, newVal -> config.fishingLineBrightness = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.alpha"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.alpha.description")))
                                        .binding(255F, () -> config.fishingLineAlpha, newVal -> config.fishingLineAlpha = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.0f", value)))
                                                .range(0F, 255F)
                                                .step(1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.speed"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.speed.description")))
                                        .binding(0.25F, () -> config.fishingLineSpeed, newVal -> config.fishingLineSpeed = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .build())
                        .build())

                // World Border

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("rendertweaks.world-border"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("rendertweaks.world-border.stationary"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.disable"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.world-border.stationary.disable.description")))
                                        .binding(false, () -> config.disableWorldBorderStationary, newVal -> config.disableWorldBorderStationary = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("rendertweaks.solid-color"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.solid-color.description")))
                                        .binding(defaults.worldBorderStationaryColor, () -> config.worldBorderStationaryColor, value -> config.worldBorderStationaryColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.enable-chroma"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.enable-chroma.description")))
                                        .binding(defaults.worldBorderStationaryChroma, () -> config.worldBorderStationaryChroma, newVal -> config.worldBorderStationaryChroma = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.saturation"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.saturation.description")))
                                        .binding(1F, () -> config.worldBorderStationarySaturation, newVal -> config.worldBorderStationarySaturation = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.brightness"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.brightness.description")))
                                        .binding(1F, () -> config.worldBorderStationaryBrightness, newVal -> config.worldBorderStationaryBrightness = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.alpha"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.alpha.description")))
                                        .binding(255F, () -> config.worldBorderStationaryAlpha, newVal -> config.worldBorderStationaryAlpha = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.0f", value)))
                                                .range(0F, 255F)
                                                .step(1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.speed"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.speed.description")))
                                        .binding(0.25F, () -> config.worldBorderStationarySpeed, newVal -> config.worldBorderStationarySpeed = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("rendertweaks.world-border.shrinking"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.disable"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.world-border.shrinking.disable.description")))
                                        .binding(false, () -> config.disableWorldBorderShrinking, newVal -> config.disableWorldBorderShrinking = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("rendertweaks.solid-color"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.solid-color.description")))
                                        .binding(defaults.worldBorderShrinkingColor, () -> config.worldBorderShrinkingColor, value -> config.worldBorderShrinkingColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.enable-chroma"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.enable-chroma.description")))
                                        .binding(defaults.worldBorderShrinkingChroma, () -> config.worldBorderShrinkingChroma, newVal -> config.worldBorderShrinkingChroma = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.saturation"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.saturation.description")))
                                        .binding(1F, () -> config.worldBorderShrinkingSaturation, newVal -> config.worldBorderShrinkingSaturation = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.brightness"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.brightness.description")))
                                        .binding(1F, () -> config.worldBorderShrinkingBrightness, newVal -> config.worldBorderShrinkingBrightness = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.alpha"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.alpha.description")))
                                        .binding(255F, () -> config.worldBorderShrinkingAlpha, newVal -> config.worldBorderShrinkingAlpha = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.0f", value)))
                                                .range(0F, 255F)
                                                .step(1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.speed"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.speed.description")))
                                        .binding(0.25F, () -> config.worldBorderShrinkingSpeed, newVal -> config.worldBorderShrinkingSpeed = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("rendertweaks.world-border.growing"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.disable"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.world-border.growing.disable.description")))
                                        .binding(false, () -> config.disableWorldBorderGrowing, newVal -> config.disableWorldBorderGrowing = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("rendertweaks.solid-color"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.solid-color.description")))
                                        .binding(defaults.worldBorderGrowingColor, () -> config.worldBorderGrowingColor, value -> config.worldBorderGrowingColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("rendertweaks.enable-chroma"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.enable-chroma.description")))
                                        .binding(defaults.worldBorderGrowingChroma, () -> config.worldBorderGrowingChroma, newVal -> config.worldBorderGrowingChroma = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.saturation"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.saturation.description")))
                                        .binding(1F, () -> config.worldBorderGrowingSaturation, newVal -> config.worldBorderGrowingSaturation = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.brightness"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.brightness.description")))
                                        .binding(1F, () -> config.worldBorderGrowingBrightness, newVal -> config.worldBorderGrowingBrightness = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.alpha"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.alpha.description")))
                                        .binding(255F, () -> config.worldBorderGrowingAlpha, newVal -> config.worldBorderGrowingAlpha = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.0f", value)))
                                                .range(0F, 255F)
                                                .step(1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("rendertweaks.speed"))
                                        .description(OptionDescription.of(Component.translatable("rendertweaks.speed.description")))
                                        .binding(0.25F, () -> config.worldBorderGrowingSpeed, newVal -> config.worldBorderGrowingSpeed = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .formatValue(value -> Component.literal(String.format("%,.1f", value)))
                                                .range(0F, 1F)
                                                .step(0.1F))
                                        .build())
                                .build())
                        .build())
        )).generateScreen(parent);
    }
}
